/* Generated by Synlig (git sha1 9a65bebd1, g++ 12.2.0-14 -fPIC -O3) */

(* top =  1  *)
(* src = "/root/synlig/synlig/tests/simple_tests/EnumFirstInInitial/top.sv:1.1-8.10" *)
module top(o);
  (* src = "/root/synlig/synlig/tests/simple_tests/EnumFirstInInitial/top.sv:1.23-1.24" *)
  output [31:0] o;
  wire [31:0] o;
endmodule
