/* Generated by Synlig (git sha1 2f1a87d62, g++ 12.2.0-14 -fPIC -O3) */

(* top =  1  *)
(* src = "/root/synlig/synlig/tests/simple_tests/DisplayWithBinFormatSpecifier/top.sv:1.1-5.10" *)
module top();
endmodule
