/* Generated by Synlig (git sha1 9705b16a7, g++ 12.2.0-14 -fPIC -O3) */

(* top =  1  *)
(* src = "/root/synlig/synlig/tests/simple_tests/ScopeOverwriting/top.sv:1.1-18.10" *)
module top();
endmodule
