/* Generated by Synlig (git sha1 d15506788, g++ 12.2.0-14 -fPIC -O3) */

(* top =  1  *)
(* src = "/root/synlig/synlig/tests/simple_tests/NestedStructs/top.sv:8.1-22.10" *)
module top();
  (* src = "/root/synlig/synlig/tests/simple_tests/NestedStructs/top.sv:16.7-16.8" *)
  (* wiretype = "\\bar1" *)
  wire a;
  (* src = "/root/synlig/synlig/tests/simple_tests/NestedStructs/top.sv:17.7-17.8" *)
  (* wiretype = "\\bar2" *)
  wire [1:0] b;
  assign a = 1'h1;
  assign b = 2'h1;
endmodule
