/* Generated by Synlig (git sha1 c799ed4e9, g++ 12.2.0-14 -fPIC -O3) */

(* top =  1  *)
(* src = "/root/synlig/synlig/tests/simple_tests/NestedCallsOfTheSameFunction/top.sv:11.1-13.10" *)
module top(o);
  (* src = "/root/synlig/synlig/tests/simple_tests/NestedCallsOfTheSameFunction/top.sv:11.23-11.24" *)
  output [31:0] o;
  wire [31:0] o;
  assign o = 32'd4;
endmodule
