/* Generated by Synlig (git sha1 90035aadd, g++ 12.2.0-14 -fPIC -O3) */

(* top =  1  *)
(* src = "/root/synlig/synlig/tests/simple_tests/MonitorInputPort/top.sv:1.1-5.10" *)
module top(a);
  (* src = "/root/synlig/synlig/tests/simple_tests/MonitorInputPort/top.sv:1.22-1.23" *)
  input [31:0] a;
  wire [31:0] a;
endmodule
